ALTER TYPE "MathBranch" ADD VALUE IF NOT EXISTS 'ALGEBRA';
ALTER TYPE "MathBranch" ADD VALUE IF NOT EXISTS 'SOLID_GEOMETRY';
ALTER TYPE "MathBranch" ADD VALUE IF NOT EXISTS 'GEOMETRY';
ALTER TYPE "MathBranch" ADD VALUE IF NOT EXISTS 'CALCULUS';
